name: Links
on:
  schedule:
    # Run at 00:00 UTC every Sunday
    - cron: '0 0 * * */7'
env:
  FORCE_COLOR: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate that links are up
        uses: simeg/urlsup-action@v1.0.0
        with:
          args: readme.md --threads 10
